# Указываем URL для подключения к базе данных H2
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Используем диалект H2 для Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Указываем, чтобы Hibernate автоматически создавал схемы и таблицы
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Включаем отображение SQL-запросов в логах
spring.jpa.show-sql=true

# Включаем консоль H2 для отладки
spring.h2.console.enabled=true

# Указываем пути для автоматического выполнения SQL-скриптов
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

